## load dataset (it should be in the same directory)
fullData <- read.table('household_power_consumption.txt', header=TRUE, sep = ';')
fullData[ fullData == "foo" ] <- NA
fullData$Date <- as.Date(fullData$Date, format='%d/%m/%Y')
fullData$Time <- sub(".*\\s+", "",  strptime(fullData$Time, format = '%H:%M:%S'))
first <- subset(test, Date >= "2007-02-01")
epcSubset <- subset(first, Date < "2007-02-03")
epcSubset$Global_active_power <- as.numeric(epcSubset$Global_active_power)
epcSubset$Sub_metering_1 <- as.numeric(epcSubset$Sub_metering_1)
epcSubset$Sub_metering_2 <- as.numeric(epcSubset$Sub_metering_2)
epcSubset$Sub_metering_3 <- as.numeric(epcSubset$Sub_metering_3)

## create the PNG file (plot3.png)
png("plot3.png", width = 480, height = 480)
plot(datetime, epcSubset$Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering")
lines(datetime, epcSubset$Sub_metering_2, col = "red")
lines(datetime, epcSubset$Sub_metering_3, col = "blue")
legend("topright", lty=c(1,1), col = c("black", "red", "blue"), legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()